'use client';

import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { ErrorBoundary } from 'react-error-boundary';
import Footer from './components/footer';
import Header from './components/header';
import ErrorFallback from './components/errorFallback';

const inter = Inter({ subsets: ['latin'] });

const queryClient = new QueryClient();

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:container md:mx-auto bg-red-400">
          <ErrorBoundary FallbackComponent={ErrorFallback}>
            <QueryClientProvider client={queryClient}>
              <Header />
              <main className="flex items-center">{children}</main>
              <Footer />
              <ReactQueryDevtools initialIsOpen />
            </QueryClientProvider>
          </ErrorBoundary>
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
